Local Mode
hoco/memcached-elasticache pull request #3
Opened 2017-02-07 10:54 UTC by hoco

Add local-mode for non-ElastiCache memcached environment.

2017-02-08 17:08 UTC, DianthuDia requested changes
👀

2017-02-08 17:08 UTC, DianthuDia commented on lib/memcached/elasticache.rb
> +      # @option [Boolean] :local_mode if local_mode is true, the client always treats the config endpoint as the only cluster endpoint (for non-ElastiCache memcached)
[nis]s/local_mode/standalone_mode

2017-02-08 17:08 UTC, DianthuDia commented on lib/memcached/elasticache/auto_discovery/endpoint.rb
> +            ConfigResponse.new("#{@host}|0.0.0.0|#{@port}")
[Q]Why don't you resolve `@host` to Ip address? It more reality.

2017-02-08 17:08 UTC, DianthuDia commented on lib/memcached/elasticache.rb
> +      # @option [Boolean] :local_mode if local_mode is true, the client always treats the config endpoint as the only cluster endpoint (for non-ElastiCache memcached)
[nits]if standalone_mode is true, the client treats `config_endpoint` as standard memcached server (NO require ElastiCache endpint). It is useful during development.

2017-02-09 05:29 UTC, hoco commented
👍

2017-02-09 06:46 UTC, DianthuDia commented on lib/memcached/elasticache/auto_discovery/endpoint.rb
> +            # IP address is not used
[IMO] 🔥 🍚

2017-02-09 08:10 UTC, merged